# Generated by Django 5.0.1 on 2024-01-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_product_unique_together_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.product'),
        ),
    ]
